recWeb/apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import generate_password_hash, check_password_hash
import enum
from datetime import datetime


# pip install shortuuid

class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4


class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(11), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    sex = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, *args, **kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop("password")
        super(FrontUser, self).__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self, rawpwd):
        return check_password_hash(self._password, rawpwd)

recWeb/apps/front/forms.py
# encoding: utf-8

from ..forms import BaseForm
from wtforms import StringField, IntegerField
from wtforms.validators import Regexp, EqualTo, ValidationError, Email, InputRequired
from utils import zlcache


class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    email = StringField(validators=[Email(message='请输入正确的邮箱格式'),
                                    InputRequired(message='邮箱不能为空')])
    username = StringField(validators=[Regexp(r".{2,20}", message='请输入正确格式的用户名！')])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo("password1", message='两次输入的密码不一致！')])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的短信验证码！')])

    def validate_graph_captcha(self, field):
        graph_captcha = field.data

        # if graph_captcha != '1111':
        graph_captcha_mem = zlcache.get(graph_captcha.lower())
        if not graph_captcha_mem:
            raise ValidationError(message='图形验证码错误！')


class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    remeber = StringField()


class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题！')])
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id！')])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入评论内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id！')])

recWeb/apps/common/views.py
import qiniu
from flask import Blueprint, request, make_response, jsonify
from utils import restful, zlcache
from io import BytesIO
from utils.captcha import Captcha

bp = Blueprint("common", __name__, url_prefix='/c')  # cms为蓝图名称、subdomain为子域名


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    zlcache.set(text.lower(), text.lower())  # 存储到memcached
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)  # 将文件指针设置为0
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


@bp.route('/uptoken/')
def uptoken():
    access_key = 'A82nBaNWAlj2pQcazU0IAdeVZUTm9zGK4N42OPIb'
    secret_key = 'ZVxmpdbLeFmJiU9f-234qG7onPh8HSXlwe95HtFB'

    q = qiniu.Auth(access_key, secret_key)

    bucket = 'rcptest2'
    token = q.upload_token(bucket)
    return jsonify({'uptoken': token})

recWeb/apps/front/__init__.py
from .views import bp
from . import hooks

recWeb/apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    url_for, g, abort, redirect
)
from .forms import SignupForm, SigninForm, AddPostForm, AddCommentForm
from utils import restful, safeutils
from .models import FrontUser
from ..models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPostModel
from exts import db
import config
from .decorators import login_required
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy.sql import func

bp = Blueprint("front", __name__)


@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get("st", type=int, default=1)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    pasts = None
    total = 0

    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精的时间倒叙排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞的数量排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论的数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    if board_id:
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()
        # PostModel.query.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0, inner_window=1)

    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort,

    }
    return render_template('front/front_index.html', **context)


@bp.route('/logout/')
@login_required
def logout():
    del session[config.FRONT_USER_ID]
    return redirect(url_for('front.signin'))


@bp.route('/profile/<user_id>', methods=['GET'])
@login_required
def profile(user_id=0):
    if not user_id:
        return abort(404)

    user = FrontUser.query.get(user_id)
    if user:
        context = {
            'current_user': user
        }
        return render_template('front/front_profile.html', **context)
    else:
        return abort(404)


@bp.route('/profile/posts/', methods=['GET'])
def profile_posts():
    user_id = request.args.get('user_id')
    if not user_id:
        return abort(404)

    user = FrontUser.query.get(user_id)
    if user:
        context = {
            'current_user': user,
        }
        return render_template('front/front_profile_posts.html', **context)
    else:
        return abort(404)


@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)

    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)


@bp.route('/acomment/', methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('没有这篇帖子！')
    else:
        return restful.params_error(form.get_error())


@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


class SignupView(views.MethodView):
    def get(self):
        # request.referrer【获取上一个页面】
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            email = form.email.data
            user = FrontUser(telephone=telephone, username=username, password=password, email=email)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())
            return restful.params_error(message=form.get_error())


class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remeber.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机号或密码错误！')
        else:
            return restful.params_error(message=form.get_error())


class ChowView(views.MethodView):
    def get(self):
        return render_template('front/shop.html')

    def post(self):
        pass


class SearchView(views.MethodView):
    def get(self):
        return render_template('front/search_index.html')

    def post(self):
        pass


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))
bp.add_url_rule('/shop/', view_func=ChowView.as_view('shop'))
bp.add_url_rule('/suggest/', view_func=SearchView.as_view('suggest'))

recWeb/templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了课堂404页面</title>
</head>
<body>
    您要找的页面已经到火星去了~~
    <div>
        <a href="/">回到首页</a>
    </div>
</body>
</html>

recWeb/templates/front/front_apost.html
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}
    发布菜谱
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static("front/js/front_apost.js") }}"></script>
{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}

            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain" style="height:500px;"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布菜谱</button>
    </div>
</form>
{% endblock %}

recWeb/templates/front/front_base.html
{% from "common/_macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include "common/_heads.html" %}
    <link rel="stylesheet" href="{{ static('front/css/front_base.css') }}">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">智慧菜谱系统</a>
        </div>
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('front.shop') }}">食材超市</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入关键字">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if g.front_user %}
                    <span id="login-tag" data-is-login="1" style="display:none;"></span>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            {{ g.front_user.username }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{{ url_for("front.profile",user_id=g.front_user.id) }}">个人中心</a></li>
                            <li><a href="#">设置</a></li>
                            <li><a href="{{ url_for('front.logout') }}">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                    <li><a href="{{ url_for("front.signup") }}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    {% block body %}
    {% block container %}{% endblock %}
    {% endblock %}
</div>
</body>
</html>

recWeb/templates/front/front_index.html
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}智慧菜谱系统{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static("front/css/front_index.css") }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
            <!-- 指示器 -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>

            <!-- 轮播图 -->
            <div class="carousel-inner" role="listbox">
                {% for banner in banners %}
                    {% if loop.first %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                        <a href="{{ banner.link_url }}">
                            <img src="{{ banner.image_url }}" alt="...">
                        </a>
                        </div>
                {% endfor %}
                        </div>

                <!-- 左右切换的控制按钮 -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="post-group">
                <ul class="post-group-head">
                    {% if current_sort == 1 %}
                        <li class="active"><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                    {% else %}
                        <li><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                    {% endif %}
                    {% if current_sort == 2 %}
                        <li class="active"><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华</a></li>
                    {% else %}
                        <li><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华</a></li>
                    {% endif %}
                    {% if current_sort == 3 %}
                        <li class="active"><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                    {% else %}
                        <li><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                    {% endif %}
                    {% if current_sort == 4 %}
                        <li class="active"><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                    {% else %}
                        <li><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                    {% endif %}
                </ul>
                <ul class="post-list-group">
                    {% for post in posts %}
                        <li>
                            <div class="author-avatar-group">
                                <img src="{{ post.author.avatar or url_for('static',filename='common/images/logo.png') }}"
                                     alt="">
                            </div>
                            <div class="post-info-group">
                                <p class="post-title">
                                    <a href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a>
                                    {% if post.highlight %}
                                        <span class="label label-danger">精华帖</span>
                                    {% endif %}
                                </p>
                                <p class="post-info">
                                    <span>作者:{{ post.author.username }}</span>
                                    <span>发表时间:{{ post.create_time }}</span>
                                    <span class="comment-count">评论数：{{ post.comments|length }}</span>
                                    <span class="read-count">阅读数：{{ post.read_count|default(0) }}</span>
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div style="text-align:center;">
                 {{ pagination.links }}
                </div>
            </div>

        </div>
        <div class="sm-container">
        <div style="padding-bottom:10px;">
            <a href="{{ url_for("front.apost") }}" class="btn btn-warning btn-block">发布菜谱</a>
        </div>
        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}
            {% for board in boards %}
                {% if board.id == current_board %}
                    <a href="{{ url_for("front.index",bd=board.id) }}"
                       class="list-group-item active">{{ board.name }}</a>
                {% else %}
                    <a href="{{ url_for("front.index",bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

recWeb/templates/front/front_profile_base.html
{% extends 'front/front_base.html' %}

{% block title %}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/front_profile_base.css') }}">
    {% block profile_head %}{% endblock %}
{% endblock %}

{% block container %}
    <div class="top-container">
        <img src="{{ current_user.avatar or url_for('static',filename='front/images/logo.png') }}"
             alt="{{ current_user.username }}" class="avatar-img">
        <div class="info">
            <p class="username">{{ current_user.username }}</p>
            <div>
                <p>积分：{{ current_user.points }}</p>
                <p>个性签名：{{ current_user.signature or '这个家伙很懒，没有留下什么~' }}</p>
            </div>
        </div>
    </div>
    <div class="bottom-container">
        <div class="left-container">
            <div class="list-group">
                <span class="list-group-item list-title">个人资料</span>
                <a href="{{ url_for('front.profile',user_id=current_user.id) }}"
                   class="list-group-item {% block profile %}{% endblock %}">
                    资料
                </a>
                <a href="{{ url_for('front.profile_posts',user_id=current_user.id) }}"
                   class="list-group-item {% block posts %}{% endblock %}">
                    菜谱</a>
                <a href="#" class="list-group-item">
                    订单</a>

            </div>
        </div>
        <div class="right-container">
            <div class="container-inner">
                {% block right_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

recWeb/templates/front/front_profile_posts.html
{% extends 'front/front_profile_base.html' %}

{% block profile_head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/front_profile_posts.css') }}">
    <script>
        $(function () {
            $('#post-btn').click(function (event) {
                event.preventDefault();
                var self = $(this);
                if(!self.hasClass('current')){
                    self.addClass('current');
                    var post_list = $(".post-list");
                    var comment_list = $('.comment-list');
                    post_list.show();
                    comment_list.hide();
                    $('#comment-btn').removeClass('current');
                }
            });
            $('#comment-btn').click(function (event) {
                event.preventDefault();
                var self = $(this);
                if(!self.hasClass('current')){
                    self.addClass('current');
                    var post_list = $(".post-list");
                    var comment_list = $('.comment-list');
                    post_list.hide();
                    comment_list.show();
                    $('#post-btn').removeClass('current');
                }
            });
        });
    </script>
{% endblock %}

{% block posts %}
active
{% endblock %}

{% block right_content %}
    <div class="theme-nav">
        <a href="#" class="theme-nav-list current" id="post-btn">菜谱</a>
        <a href="#" id="comment-btn" class="theme-nav-list">回复</a>
    </div>
    <div class="post-list">
        <table class="table">
            <thead>
                <th>标题：</th>
                <th>板块</th>
                <th>回复/查看</th>
            </thead>
            <tbody>
                {% for post in current_user.posts %}
                    <tr>
                        <td><a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a></td>
                        <td>{{ post.board.name }}</td>
                        <td>{{ post.comments|length }}/{{ post.read_count|default(0) }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="comment-list" style="display: none;">
        <table class="table">
            <thead>
                <th>评论</th>
                <th>板块</th>
            </thead>
            <tbody>
                {% for comment in current_user.comments %}
                    <tr>
                        <td>
                            <p>
                                帖子：<a href="{{ url_for('front.post_detail',post_id=comment.post.id) }}">{{ comment.post.title }}</a>
                            </p>
                            <p class="comment-p">{{ comment.content|safe }}</p>
                        </td>
                        <td>{{ comment.post.board.name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

recWeb/templates/front/front_signin.html
{% extends 'front/front_signbase.html' %}
{% from "common/_macros.html" import static %}

{% block title %}
    系统登录
{% endblock %}

{% block head %}
    <script src="{{ static("front/js/front_signin.js") }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ static("front/css/reset.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ static("front/css/main.css") }}">
{% endblock %}

{% block h2_block %}

{% endblock %}

{% block signbox %}
        <div class="form-group">
            <input type="text" class="form-control" name="telephone" placeholder="手机号码">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="密码">
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" name="remember" value="1">记住我
            </label>
        </div>
        <div class="form-group">
            <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
        </div>
        <div class="form-group">
            <a href="{{ url_for("front.signup") }}" class="signup-link">没有账号？立即注册</a>
            <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
        </div>
{% endblock %}

recWeb/templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    注册
{% endblock %}

{% block head %}
    <script src="{{ static('front/js/front_signup.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ static("front/css/reset.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ static("front/css/main.css") }}">
{% endblock %}

{% block h2_block %}
       <div class="reg_slogan" style="text-align: left"><a href="/">智慧菜谱系统</a></div>
{% endblock %}

{% block signbox %}

    <div class="register_con">

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="#">登录</a>
            </div>
            <div class="reg_form clearfix">
                    <ul>
                        <li>
                            <div class="form-group">
                                <label>用户名:</label>
                                <input type="text" class="form-control" name="username" placeholder="">
                            </div>
                        </li>
                        <li>
                            <div class="form-group">
                                <label>密码:</label>
                                <input type="password" class="form-control" name="password1" placeholder="">
                            </div>
                        </li>
                        <li>
                            <div class="form-group">
                                <label>确认密码:</label>
                                <input type="password" class="form-control" name="password2" placeholder="">
                            </div>
                        </li>
                        <li>
                            <div class="form-group">
                                <label>邮箱:</label>
                                <input type="text" class="form-control" name="sms_captcha" placeholder="">
                            </div>
                        </li>
                        <li>
                            <div class="form-group">

                                <label>手机号码:</label>
                                <input type="text" class="form-control" name="telephone" placeholder="">

                            </div>

                        </li>
                        <li>
                            <div class="form-group">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
                                    <span class="input-group-addon captcha-addon">
                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">
            </span>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="form-group">
                                <span style="display: none" id="return-to-span">{{ return_to }}</span>
                                <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
                            </div>
                        </li>
                            <div class="form-group">
                                <input type="checkbox" name="allow" id="allow" checked="checked">
                                <label>同意”智慧菜谱系统的使用协议“</label>
                            </div>
                    </ul>
            </div>
        </div>

    </div>


{% endblock %}